// Routes shown on the site, with forecast coordinates
export const ROUTES = [
  { name: 'Ardrossan - Brodick (Arran)',                   lat: 55.58, lon: -5.09 },
  { name: 'Troon - Brodick (Arran)',                       lat: 55.53, lon: -4.97 },
  { name: 'Kennacraig - Port Ellen / Port Askaig (Islay)', lat: 55.87, lon: -5.50 },
  { name: 'Oban - Craignure (Mull)',                       lat: 56.41, lon: -5.47 },
  { name: 'Oban - Coll / Tiree',                          lat: 56.62, lon: -6.52 },
  { name: 'Oban - Colonsay',                              lat: 56.07, lon: -6.19 },
  { name: 'Oban - Castlebay / Lochboisdale',              lat: 56.95, lon: -7.32 },
  { name: 'Mallaig - Armadale (Skye)',                    lat: 57.06, lon: -5.83 },
  { name: 'Ullapool - Stornoway (Lewis)',                  lat: 58.20, lon: -6.39 },
  { name: 'Uig - Tarbert / Lochmaddy',                    lat: 57.73, lon: -6.96 },
  { name: 'Gourock - Dunoon',                             lat: 55.96, lon: -4.92 },
  { name: 'Wemyss Bay - Rothesay (Bute)',                 lat: 55.84, lon: -5.05 },
  { name: 'Colintraive - Rhubodach (Bute)',               lat: 55.92, lon: -5.15 },
  { name: 'Largs - Cumbrae Slip',                         lat: 55.79, lon: -4.87 },
  { name: 'Tarbert - Portavadie',                         lat: 55.87, lon: -5.41 },
  { name: 'Claonaig - Lochranza (Arran)',                 lat: 55.70, lon: -5.39 },
  { name: 'Tobermory - Kilchoan',                         lat: 56.62, lon: -6.08 },
  { name: 'Fishnish - Lochaline',                         lat: 56.52, lon: -5.73 },
  { name: 'Mallaig - Small Isles',                        lat: 56.97, lon: -6.30 },
  { name: 'Oban - Lismore',                               lat: 56.50, lon: -5.49 },
  { name: 'Seil - Luing',                                 lat: 56.23, lon: -5.62 },
  { name: 'Port Askaig - Feolin (Jura)',                  lat: 55.85, lon: -6.10 },
];

// Port coordinates for the vessel tracker map
export const ROUTE_PORTS = {
  'Ullapool - Stornoway (Lewis)':                    { a:[57.897,-5.163,'Ullapool'],       b:[58.209,-6.388,'Stornoway'] },
  'Troon - Brodick (Arran)':                         { a:[55.551,-4.666,'Troon'],           b:[55.576,-5.135,'Brodick'] },
  'Ardrossan - Brodick (Arran)':                     { a:[55.638,-4.820,'Ardrossan'],       b:[55.576,-5.135,'Brodick'] },
  'Oban - Craignure (Mull)':                         { a:[56.415,-5.471,'Oban'],            b:[56.467,-5.706,'Craignure'] },
  'Kennacraig - Port Ellen / Port Askaig (Islay)':   { a:[55.789,-5.479,'Kennacraig'],      b:[55.629,-6.191,'Port Ellen'] },
  'Wemyss Bay - Rothesay (Bute)':                    { a:[55.876,-4.893,'Wemyss Bay'],      b:[55.837,-5.053,'Rothesay'] },
  'Gourock - Dunoon':                                { a:[55.956,-4.818,'Gourock'],         b:[55.950,-4.927,'Dunoon'] },
  'Tarbert - Portavadie':                            { a:[55.867,-5.407,'Tarbert'],         b:[55.876,-5.313,'Portavadie'] },
  'Fishnish - Lochaline':                            { a:[56.519,-5.729,'Fishnish'],        b:[56.537,-5.775,'Lochaline'] },
  'Mallaig - Armadale (Skye)':                       { a:[57.005,-5.828,'Mallaig'],         b:[57.067,-5.897,'Armadale'] },
  'Uig - Tarbert / Lochmaddy':                       { a:[57.588,-6.358,'Uig'],             b:[57.899,-6.798,'Tarbert (Harris)'] },
  'Oban - Coll / Tiree':                             { a:[56.415,-5.471,'Oban'],            b:[56.619,-6.523,'Coll / Tiree'] },
  'Oban - Castlebay / Lochboisdale':                 { a:[56.415,-5.471,'Oban'],            b:[56.951,-7.488,'Castlebay'] },
  'Oban - Colonsay':                                 { a:[56.415,-5.471,'Oban'],            b:[56.079,-6.189,'Colonsay'] },
  'Claonaig - Lochranza (Arran)':                    { a:[55.750,-5.368,'Claonaig'],        b:[55.704,-5.296,'Lochranza'] },
  'Colintraive - Rhubodach (Bute)':                  { a:[55.924,-5.148,'Colintraive'],     b:[55.931,-5.135,'Rhubodach'] },
  'Largs - Cumbrae Slip':                            { a:[55.796,-4.869,'Largs'],           b:[55.793,-4.893,'Cumbrae Slip'] },
  'Oban - Lismore':                                  { a:[56.415,-5.471,'Oban'],            b:[56.496,-5.508,'Lismore'] },
  'Mallaig - Small Isles':                           { a:[57.005,-5.828,'Mallaig'],         b:[56.876,-6.148,'Small Isles'] },
  'Tobermory - Kilchoan':                            { a:[56.622,-6.069,'Tobermory'],       b:[56.696,-6.099,'Kilchoan'] },
};

// Route info data — crossing time, scheduled vessel, notes
export const ROUTE_INFO = {
  'Ardrossan - Brodick (Arran)':              { crossing: '55 min', vessel: 'MV Caledonian Isles', vessel2: 'MV Glen Sannox (Troon)', type: 'Vehicle ferry', note: 'Busiest CalMac route' },
  'Troon - Brodick (Arran)':                  { crossing: '50 min', vessel: 'MV Glen Sannox', vessel2: 'MV Alfred', type: 'Vehicle ferry', note: 'Operates when Ardrossan unavailable' },
  'Kennacraig - Port Ellen / Port Askaig (Islay)': { crossing: '2h 20min', vessel: 'MV Finlaggan', vessel2: 'MV Isle of Islay', type: 'Vehicle ferry', note: 'Two ports served — check your destination' },
  'Oban - Craignure (Mull)':                  { crossing: '45 min', vessel: 'MV Isle of Mull', vessel2: 'MV Loch Frisa', type: 'Vehicle ferry', note: 'Up to 20 sailings/day in summer' },
  'Ullapool - Stornoway (Lewis)':             { crossing: '2h 45min', vessel: 'MV Loch Seaforth', type: 'Vehicle ferry', note: 'The Minch — can be rough in winter' },
  'Wemyss Bay - Rothesay (Bute)':            { crossing: '35 min', vessel: 'MV Argyle / MV Bute', type: 'Vehicle ferry', note: 'Very frequent — up to 24/day' },
  'Gourock - Dunoon':                         { crossing: '20 min', vessel: 'MV Ali Cat / MV Argyll Flyer', type: 'Passenger only', note: 'Western Ferries also operates nearby (vehicles)' },
  'Tarbert - Portavadie':                     { crossing: '25 min', vessel: 'MV Loch Tarbert', type: 'Vehicle ferry', note: 'Hourly service in summer' },
  'Fishnish - Lochaline':                     { crossing: '15 min', vessel: 'MV Loch Linnhe', type: 'Vehicle ferry', note: 'Shortest Mull crossing — no booking needed' },
  'Mallaig - Armadale (Skye)':               { crossing: '30 min', vessel: 'MV Coruisk / MV Loch Fyne', type: 'Vehicle ferry', note: 'Seasonal (summer timetable only)' },
  'Uig - Tarbert / Lochmaddy':               { crossing: '1h 40min', vessel: 'MV Hebrides', type: 'Vehicle ferry', note: 'Uig triangle — Harris & North Uist' },
  'Oban - Coll / Tiree':                      { crossing: '3h / 4h', vessel: 'MV Clansman', type: 'Vehicle ferry', note: 'Exposed western route, day-specific timetable' },
  'Oban - Castlebay / Lochboisdale':          { crossing: '5h+', vessel: 'MV Isle of Lewis', type: 'Vehicle ferry', note: 'Barra & South Uist — overnight possible' },
  'Oban - Colonsay':                          { crossing: '2h 20min', vessel: 'MV Lord of the Isles', type: 'Vehicle ferry', note: 'Seasonal — limited sailings' },
  'Claonaig - Lochranza (Arran)':             { crossing: '30 min', vessel: 'MV Catriona', type: 'Vehicle ferry', note: 'Seasonal summer service only' },
  'Colintraive - Rhubodach (Bute)':           { crossing: '5 min', vessel: 'MV Loch Dunvegan', type: 'Vehicle ferry', note: 'Shortest CalMac crossing' },
  'Largs - Cumbrae Slip':                     { crossing: '10 min', vessel: 'MV Argyll', type: 'Vehicle ferry', note: 'Very frequent — turn up and go' },
  'Oban - Lismore':                           { crossing: '50 min', vessel: 'MV Loch Striven', type: 'Vehicle ferry', note: 'Port Appin seasonal alternative also exists' },
  'Mallaig - Small Isles':                    { crossing: '1–4h', vessel: 'MV Lochnevis', type: 'Vehicle ferry', note: 'Serves Eigg, Muck, Rùm and Canna — tidal dependent' },
  'Tobermory - Kilchoan':                     { crossing: '35 min', vessel: 'MV Loch Riddon', type: 'Vehicle ferry', note: 'Ardnamurchan Peninsula access' },
};
